baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# -----------------------------------------------------------------------------
# Plugins settings
# -----------------------------------------------------------------------------

# Jekyll Polyglot
languages: ["en-us", "pt-br"]
default_lang: "pt-br"
exclude_from_localization: ["assets"]
lang_from_path: true
parallel_localization: false

jekyll-minifier:
  # exclude: ["robots.txt"]
  uglifier_args:
    harmony: true

# Jekyll Animate Elements
animation:
  enabled: true
  selector: "audio, blockquote, div.card, div.highlighter-rouge, div.news, div.repositories, div.row, div.social, div.tag-category-list, figure, h2, h3, input, ol, p, tr, ul, video"

# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------
exclude:
  - .git/
  - .github/
  - .gitignore
  - .ruby-version
  - readme_img/
  - LICENSE
  - README.md
  - run_on_code_changed.sh

include: ["_pages"]

plugins:
  - jekyll-3rd-party-libraries
  - jekyll-animate-elements
  - jekyll-cache-bust
  - jekyll-dotenv
  - jekyll-minifier
  - jekyll-polyglot

sass:
  sourcemap: never
  style: compressed

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

# Add the url, version and integrity hash of the libraries you use in your site.
# The integrity hash is used to ensure that the library is not tampered with.
# Integrity hashes not provided by the libraries were generated using https://www.srihash.org/

third_party_libraries:
  download: false # if true, download the versions of the libraries specified below and use the downloaded files
  bootstrap:
    integrity:
      css: "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      js: "sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap@{{version}}/dist/css/bootstrap.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap@{{version}}/dist/js/bootstrap.bundle.min.js"
    version: "5.3.3"
  firebase-app:
    integrity:
      js: "sha384-..."
    url:
      js: "https://www.gstatic.com/firebasejs/{{version}}/firebase-app-compat.js"
    version: "9.6.7"
  firebase-auth:
    integrity:
      js: "sha384-..."
    url:
      js: "https://www.gstatic.com/firebasejs/{{version}}/firebase-auth-compat.js"
    version: "9.6.7"
  firebase-firestore:
    integrity:
      js: "sha384-..."
    url:
      js: "https://www.gstatic.com/firebasejs/{{version}}/firebase-firestore-compat.js"
    version: "9.6.7"
  font-awesome:
    integrity:
      css: "sha256-XfA0ppGOANs88Ds+9FqVLy3xIGzT/25K/VLmRRxE9ow="
      js: "sha256-qq1ob4lpAizCQs1tkv5gttMXUlgpiHyvG3JcCIktRvs="
    url:
      css: "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@{{version}}/css/fontawesome.min.css"
      js: "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@{{version}}/js/all.min.js"
    version: "6.6.0"
  fuse:
    integrity:
      js: "sha256-Igk09XYTSwRm2Z94bOIbE/h9MZsemuYzxV5o9vQcPJ0="
    url:
      js: "https://cdn.jsdelivr.net/npm/fuse.js@{{version}}/dist/fuse.min.js"
    version: "7.1.0"
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  luxon:
    integrity:
      js: "sha256-/TZdvWBQbZdgT95AgMF6nDLyjhe3QdOMpw4VLnkcgq4="
    url:
      js: "https://cdn.jsdelivr.net/npm/luxon@{{version}}/build/global/luxon.min.js"
    version: "3.5.0"
  mdb:
    integrity:
      css: "sha256-m1+5a1JnsNbgocEqeccYA0D6eQWJSYLHJeSGN8xIVPA="
      js: "sha512-z2TpMCfA7shP7qK/58k3WvdKLCFthQVrsfq+qsOjtVzk6QRE5mYgs6rd8pjtbtuqZtOJt8Q/IGpacrteVcoUpA=="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdb-ui-kit@{{version}}/css/mdb.min.css"
      js: "https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/{{version}}/mdb.umd.min.js"
    version: "8.0.0"
